---
- hosts: web
  tasks:
    - name: Install apache2
      apt:
        name: apache2
    - name: Start apache2
      service: 
        name: apache2
        state: started
    - name: Install index.html
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data    
        mode: '0644'